### ISSUE TITLE
Bug: "sunrise" not found

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [FrancescoRigoni/CollapsingToolbarController#1]
Can't build the project because of it.

Also, some suggestions:

1. Make this a library&sample repository, so that others could use it easily, using Gradle.
2. In the sample, show how to combine this solution together with what can be done to avoid the "wobbly" bug as shown here: https://stackoverflow.com/q/45192654/878126
3.  Make a class that extends from `AppBarLayout` which has all the extra functions of `CollapsingToolbarController` .

Maybe something like that:

    class AppBarLayoutEx : AppBarLayout {
        private var isAppBarExpanded = true
        private val behavior = AppBarLayoutBehavior()
        private var onStateChangedListener: (Boolean) -> Unit = {}
        var enableExpandAndCollapseByDraggingToolbar: Boolean
            get() = behavior.canDrag
            set(value) {
                behavior.canDrag = value
            }
    
        var enableExpandAndCollapseByDraggingContent: Boolean
            get() = behavior.acceptsNestedScroll
            set(value) {
                behavior.acceptsNestedScroll = value
            }
    
        constructor(context: Context) : super(context)
        constructor(context: Context, attrs: AttributeSet) : super(context, attrs)
    
        init {
            addOnOffsetChangedListener(
                    AppBarLayout.OnOffsetChangedListener { _, verticalOffset ->
                        isAppBarExpanded = verticalOffset == 0
                        onStateChangedListener(isAppBarExpanded)
                    })
        }
    
        override fun setLayoutParams(params: ViewGroup.LayoutParams?) {
            super.setLayoutParams(params)
            (params as CoordinatorLayout.LayoutParams).behavior = behavior
        }
    
        fun toggleExpandedState() {
            setExpanded(!isAppBarExpanded, true)
        }
    
        fun setOnExpandAndCollapseListener(onStateChangedListener: (Boolean) -> Unit) {
            this.onStateChangedListener = onStateChangedListener
        }
    
        private class AppBarLayoutBehavior : AppBarLayout.Behavior() {
            var canDrag = true
            var acceptsNestedScroll = true
    
            init {
                setDragCallback(object : AppBarLayout.Behavior.DragCallback() {
                    override fun canDrag(appBarLayout: AppBarLayout) = canDrag
                })
            }
    
            override fun onStartNestedScroll(parent: CoordinatorLayout, child: AppBarLayout, directTargetChild: View,
                                             target: View, nestedScrollAxes: Int, type: Int) = acceptsNestedScroll
        }
    }

Usage:

    class MainActivity : AppCompatActivity() {
    
        override fun onCreate(savedInstanceState: Bundle?) {
            super.onCreate(savedInstanceState)
            setContentView(R.layout.activity_main)
            setSupportActionBar(toolbar)
            appBarLayout.setOnExpandAndCollapseListener { expanded ->
                btCollapseExpand.text = if (expanded) "Collapse" else "Expand"
            }
    
            checkBoxDisableDragToolbar.setOnCheckedChangeListener { _, isChecked ->
                appBarLayout.enableExpandAndCollapseByDraggingToolbar = !isChecked
            }
    
            checkBoxDisableScrolling.setOnCheckedChangeListener { _, isChecked ->
                appBarLayout.enableExpandAndCollapseByDraggingContent = !isChecked
            }
    
            btCollapseExpand.setOnClickListener {
                appBarLayout.toggleExpandedState()
            }
        }
    }

**Comment by FrancescoRigoni** [comment]
Thanks for reporting the issue, I'll fix it asap.

**Comment by AndroidDeveloperLB** [comment]
Thank you

**Comment by FrancescoRigoni** [comment]
@AndroidDeveloperLB it should be fixed now, thanks for the heads up :)

**Comment by AndroidDeveloperLB** [comment]
Thank you.
Please consider the suggestions.
